apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: configuration.admin.bootifulpodcast.online.
  labels:
    app: configuration
  name: configuration
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: configuration
  type: LoadBalancer

