name: Deploy Infrastructure


env:

  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  CONFIGURATION_SERVER_USERNAME: ${{ secrets.CONFIGURATION_SERVER_USERNAME }}
  CONFIGURATION_SERVER_PASSWORD: ${{ secrets.CONFIGURATION_SERVER_PASSWORD }}
  GCLOUD_ZONE_DEVELOPMENT: ${{ secrets.GCLOUD_ZONE_DEVELOPMENT }}
  GCLOUD_PROJECT_DEVELOPMENT: ${{ secrets.GCLOUD_PROJECT_DEVELOPMENT }}
  GCLOUD_SA_KEY: ${{ secrets.GCLOUD_SA_KEY }}


on:
  create:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: "Setup Initial Environment"
        run: |
          source $GITHUB_WORKSPACE/.github/workflows/bp_mode.sh

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Setup GCP environment
        uses: GoogleCloudPlatform/github-actions@0.1.2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: ${{ env.GCLOUD_PROJECT }}

      - run: |-
          gcloud config set project $GCLOUD_PROJECT
          gcloud --quiet auth configure-docker


      - run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone "$GCLOUD_ZONE" --project $GCLOUD_PROJECT


      - name: Deploy Spring Cloud Config Server
        run: |
          cd $GITHUB_WORKSPACE/deploy
          export APP_NAME=configuration
          ./build.sh
          ./deploy.sh

